[[redirects]]
  force = true
  from = "/"
  to = "https://glittery-otter-ddfc65.netlify.app/callback"
  status = 200
  [redirect.headers]
    x-from = "Netlify"
[[redirects]]
  force = true
  from = "/callback"
  to = "https://glittery-otter-ddfc65.netlify.app/main"
  status = 200
  [redirect.headers]
    x-from = "Netlify"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200